name: Build and Test
run-name: Execute ci/cd workflow
on: [push]
jobs:
    install-cmake:
        name: Install CMAKE
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install CMAKE
              run: sudo apt update && sudo apt install -y cmake

    install-mpi:
        name: Install MPI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install MPI
              run: sudo apt update && sudo apt install -y mpich
    
    build-project:
        name: Build Project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Create build directory
              run: mkdir build
            - name: Build project
              run: cmake -B ./build/ && make
    
    # run-tests:
    #     name: Run code tests
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v2
    #         - run: echo "Executing tests"
    #         - run: ./test_multiplication